"""harden_database_schema_and_types

Revision ID: 1993db1a6e59
Revises: 4fdb43b6360d
Create Date: 2026-07-11 22:35:01.062927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1993db1a6e59'
down_revision: Union[str, Sequence[str], None] = '4fdb43b6360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('limit_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('needs_review', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_transactions_user_id_date', ['user_id', 'transaction_date'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_budget',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_budget',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_id_date')
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_source'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_transactions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('needs_review')
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('limit_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
