"""add razorpay billing fields to user

Revision ID: 70e9f59f1826
Revises: 5619a9d81c54
Create Date: 2026-07-12 15:50:38.345466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e9f59f1826'
down_revision: Union[str, Sequence[str], None] = '5619a9d81c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('razorpay_subscription_id')
        batch_op.drop_column('razorpay_customer_id')
        batch_op.drop_column('is_pro')

    # ### end Alembic commands ###
